# Generated by Django 5.2.8 on 2025-11-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='registration_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
