# Generated by Django 5.2.8 on 2025-11-17 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_enrollment_schedule_alter_enrollment_student'),
        ('attendance', '0003_fix_class_session_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_session', to='academic.schedule'),
        ),
    ]
