# Generated by Django 5.2.7 on 2025-10-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=60)),
                ('student_id', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=200)),
                ('major', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=60)),
                ('profesor_id', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=200)),
                ('department', models.CharField(max_length=80)),
            ],
        ),
    ]
